default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "mld") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: dfa_backend_development

test:
  <<: *default
  database: dfa_backend_test

production:
  <<: *default
  database: dfa_backend_production

cable:
  <<: *default
  database: dfa_backend_production

queue:
  <<: *default
  database: dfa_backend_production
<<<<<<< HEAD
=======

cache:
  <<: *default
  database: dfa_backend_production
>>>>>>> 1c233bf91dcb1279182e0af3d2554889b17cddd9
